name: CI Pipeline

on:
  push:
    branches:
      - api-feature
  pull_request:
    branches:
      - api-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CI script
        run: echo "CI Build Passed"
